const NAVIGATION_EVENT_CATEGORY = "NAVIGATION";
const NAVIGATION_EVENT_NAME = "Route_Request";
const DEFAULT_SCOPES = ["analytics:website:tracking"];

export { NAVIGATION_EVENT_CATEGORY, NAVIGATION_EVENT_NAME, DEFAULT_SCOPES };
